[package]
name = "rust"
version = "0.1.0"
authors = ["吴翱翔 <pylint@yandex.com>"]
edition = "2018"


[lib]
crate-type = ["dylib"]

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "*", default-features = false }

[dependencies]
